[workspace]
members = ["canvas-cli", "canvas-core", "canvas-models"]
resolver = "2"

[workspace.package]
edition = "2024"
rust-version = "1.92"
license = "MIT"

[workspace.dependencies]
canvas-core = { path = "canvas-core" }
canvas-models = { path = "canvas-models" }
clap = { version = "4.5.54", features = ["derive"] }
thiserror = "2.0.17"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = "warn"
unwrap_used = "warn"
expect_used = "warn"
